# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec1a36578134d2f4edc4e1e744c524221307e4eec1ef75b41cf7b08c65922a9c58fd375aafd689ad449075892c0ddb8e80c6e8409e87becd4f6a1340c11e28e0

test:
  secret_key_base: 820d9f479030417053c276eebe1b07b86c976d1cd151b2feb7c749306e9085f902de76f519e9a413bccedd3a9a9549ae8bcdc0014160634ebc40cbbd0eef64e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
